# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

5.times do |iteration|
  Product.create(title: "Product ##{iteration}", description: "This is the #{iteration} product generated by seeds", goal: 100, image_url: "http://www.mckinleysgroup.com/images/ww/product/frommerlin/A2639.jpg")
end
