# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Generate Projects
5.times do |iteration|
  Product.create(title: "Product ##{iteration}", description: "This is the #{iteration} product generated by seeds", goal: 100, start_date: "2016-09-22 12:00:00", end_date: "2016-11-22 12:00:00", user_id: 1, image_url: "http://www.mckinleysgroup.com/images/ww/product/frommerlin/A2639.jpg")
end


# Generate users
3.times do |iteration|
  User.create(name: "User ##{iteration}", email: "user#{iteration}@example.com", password_digest: "#{iteration}#{iteration}#{iteration}#{iteration}")
end

Reward.new(title: "1st reward", description: "description", amount: 100)
Pledge.new(user_id: 1, product_id: 1, reward_id: 1, amount: 100)
